services:
  - type: web
    name: luke-the-plumber
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn luke_plumber.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.3"
