# Generated by Django 5.2.17 on 2026-08-28 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon', models.CharField(default='bi-wrench', help_text="Bootstrap Icons class, e.g. 'bi-droplet-fill', 'bi-fire', 'bi-wrench'.", max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text="Optional 'prices from' figure shown on the service card.", max_digits=8, null=True)),
                ('is_emergency', models.BooleanField(default=False, help_text='Show this service on the 24/7 emergency callout section.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order (lowest first).')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(help_text="e.g. 'Clapham, London'", max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(help_text='Property address, including postcode.', max_length=255)),
                ('is_emergency', models.BooleanField(default=False, help_text='Tick if this is an urgent/emergency job.')),
                ('message', models.TextField(help_text='Describe the job / issue.')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_notified', models.BooleanField(default=False, help_text='Whether the WhatsApp alert to the admin was sent successfully.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
